changelog:
  exclude:
    labels:
      - ignore-for-release
      - skip-changelog
    authors:
      - dependabot
  categories:
    - title: ✨ Features
      labels:
        - feature
        - enhancement
    - title: 🐛 Bug Fixes
      labels:
        - bugfix
        - fix
    - title: 📦 Dependencies
      labels:
        - dependencies
    - title: ⚡️ Performance
      labels:
        - performance
    - title: 📝 Documentation
      labels:
        - documentation
    - title: Other Changes
      labels:
        - "*"
